spring.application.name=api-gatewayV2
server.port=8766


eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.mvc.routes[0].id=course-service
spring.cloud.gateway.mvc.routes[0].uri=lb://course-service
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/course-service/**
spring.cloud.gateway.mvc.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.mvc.routes[1].id=studnet-service
spring.cloud.gateway.mvc.routes[1].uri=lb://studnet-service
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/studnet-service/**
spring.cloud.gateway.mvc.routes[1].filters[0]=StripPrefix=1